//fitness calculator
exports.bmi = require('./lib/fitness/bmi')
exports.bodyFat = require('./lib/fitness/bodyFat')
exports.bmr = require('./lib/fitness/bmr')
exports.idealWeight = require('./lib/fitness/idealWeight')
exports.pace = require('./lib/fitness/pace')
exports.armyBody = require('./lib/fitness/armyBodyFat')
exports.calorie = require('./lib/fitness/calorie')
exports.lbm = require('./lib/fitness/lbm')
exports.healthyWeight = require('./lib/fitness/healthyWeight')
exports.caloriesBurn = require('./lib/fitness/caloriesBurn')

//pregnancy calculator
exports.pregnancyWeightGain = require('./lib/pregnancy/pregnancyWeightGain')
exports.ovulation = require('./lib/pregnancy/ovulation')
exports.conception = require('./lib/pregnancy/conception')
exports.period = require('./lib/pregnancy/period')
exports.estimateDate = require('./lib/pregnancy/estimateDeliveryDate')
exports.pregnancy = require('./lib/pregnancy/pregnancy')

//other calculator
exports.macro = require('./lib/others/macro')
exports.tdee = require('./lib/others/tdee')
exports.gfr = require('./lib/others/gfr')
exports.bsa = require('./lib/others/bsa')
exports.carbohydrate = require('./lib/others/carbohydrate')
exports.protein = require('./lib/others/protein')
exports.fat = require('./lib/others/fat')
exports.bac = require('./lib/others/bac')
exports.bodyType = require('./lib/others/bodyType')