exports.bmi = require('./lib/fitness/bmi')
exports.body_fat = require('./lib/fitness/body_fat')
exports.bmr = require('./lib/fitness/bmr')
exports.idealWeight = require('./lib/fitness/idealWeight')
exports.pace = require('./lib/fitness/pace')
exports.armyBody = require('./lib/fitness/armyBodyFat')
exports.calorie = require('./lib/fitness/calorie')